/** Major US & Canada gateways Gatherwell can quote from. Code stored, city shown. */
export const AIRPORTS: { code: string; city: string }[] = [
  { code: "ATL", city: "Atlanta" },
  { code: "AUS", city: "Austin" },
  { code: "BNA", city: "Nashville" },
  { code: "BOS", city: "Boston" },
  { code: "BWI", city: "Baltimore" },
  { code: "CLT", city: "Charlotte" },
  { code: "CVG", city: "Cincinnati" },
  { code: "DCA", city: "Washington National" },
  { code: "DEN", city: "Denver" },
  { code: "DFW", city: "Dallas–Fort Worth" },
  { code: "DTW", city: "Detroit" },
  { code: "EWR", city: "Newark" },
  { code: "FLL", city: "Fort Lauderdale" },
  { code: "HNL", city: "Honolulu" },
  { code: "IAD", city: "Washington Dulles" },
  { code: "IAH", city: "Houston" },
  { code: "IND", city: "Indianapolis" },
  { code: "JFK", city: "New York JFK" },
  { code: "LAS", city: "Las Vegas" },
  { code: "LAX", city: "Los Angeles" },
  { code: "LGA", city: "New York LaGuardia" },
  { code: "MCI", city: "Kansas City" },
  { code: "MCO", city: "Orlando" },
  { code: "MDW", city: "Chicago Midway" },
  { code: "MIA", city: "Miami" },
  { code: "MSP", city: "Minneapolis–St. Paul" },
  { code: "MSY", city: "New Orleans" },
  { code: "NAS", city: "Nassau" },
  { code: "OAK", city: "Oakland" },
  { code: "ORD", city: "Chicago O'Hare" },
  { code: "PDX", city: "Portland" },
  { code: "PHL", city: "Philadelphia" },
  { code: "PHX", city: "Phoenix" },
  { code: "PIT", city: "Pittsburgh" },
  { code: "RDU", city: "Raleigh–Durham" },
  { code: "SAN", city: "San Diego" },
  { code: "SAT", city: "San Antonio" },
  { code: "SEA", city: "Seattle" },
  { code: "SFO", city: "San Francisco" },
  { code: "SJC", city: "San Jose" },
  { code: "SLC", city: "Salt Lake City" },
  { code: "SMF", city: "Sacramento" },
  { code: "STL", city: "St. Louis" },
  { code: "TPA", city: "Tampa" },
  // Canada
  { code: "YEG", city: "Edmonton" },
  { code: "YHZ", city: "Halifax" },
  { code: "YLW", city: "Kelowna" },
  { code: "YOW", city: "Ottawa" },
  { code: "YQB", city: "Quebec City" },
  { code: "YQR", city: "Regina" },
  { code: "YXE", city: "Saskatoon" },
  { code: "YUL", city: "Montreal" },
  { code: "YVR", city: "Vancouver" },
  { code: "YWG", city: "Winnipeg" },
  { code: "YYC", city: "Calgary" },
  { code: "YYJ", city: "Victoria" },
  { code: "YYZ", city: "Toronto Pearson" },
];
