/** The Gatherwell Destination Library. Curated by Gatherwell Travel; matched by the group's own votes. */
export type Destination = {
  id: string; name: string; country: string;
  haul: 1 | 2 | 3;            // 1 short (<3h) · 2 medium (3-6h) · 3 long (6h+)
  budget: 1 | 2 | 3 | 4;     // 1 budget · 2 mid · 3 premium · 4 luxury
  climate: string[];          // hot | warm | crisp | snow
  setting: string[];          // ocean | mountain | city | country
  villa: 0 | 1 | 2; kids: 0 | 1 | 2; nightlife: 0 | 1 | 2;
  usNoPassport: boolean; months: string; blurb: string; sig: string[];
  picks?: { t: string; s: string }[];  // Gatherwell insider products (customer-safe)
};

export const DESTINATIONS: Destination[] = [
  { id: "riviera-maya", name: "Riviera Maya", country: "Mexico", haul: 1, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 2, usNoPassport: false, months: "Best Nov\u2013Apr", blurb: "The best-served beach hub in Latin America: villas, all-inclusives, cenotes, and ruins.", sig: ["catamaran day", "cenote snorkel", "Tulum ruins"], picks: [{ t: "Hyatt Impression by Secrets Isla Mujeres", s: "Only 123 rooms" }, { t: "Hyatt Impression by Secrets Moxch\u00e9", s: "Boutique resort in Playa del Carmen" }, { t: "Hyatt Secrets Akumal", s: "Akumal = place of turtles" }] },
  { id: "punta-cana", name: "Punta Cana", country: "Dominican Republic", haul: 2, budget: 1, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 2, nightlife: 1, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "The easiest all-inclusive week in the Caribbean, built for big easy groups.", sig: ["catamaran + snorkel", "Saona Island", "swim-up everything"], picks: [{ t: "Hyatt Silara Capcana", s: "Amazing service" }, { t: "Hyatt Ziva Tuscana", s: "Family-friendly" }, { t: "Hyatt Secrets Capcana Dominican Republic", s: "15 minutes from airport" }] },
  { id: "los-cabos", name: "Los Cabos", country: "Mexico", haul: 2, budget: 3, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 1, nightlife: 2, usNoPassport: false, months: "Best Oct\u2013Jun", blurb: "Desert-meets-sea luxury with the best staffed-villa scene in North America.", sig: ["private boat day", "whale watching (Dec\u2013Apr)", "tequila tasting"] },
  { id: "jamaica", name: "Montego Bay & Negril", country: "Jamaica", haul: 1, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 2, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "Staffed villas with cooks are a Jamaican art form; reggae and river rafting close by.", sig: ["Dunn's River Falls", "catamaran sunset", "jerk cooking"], picks: [{ t: "Sandals Doze River Jamaica", s: "Open-air squeeze and rum bus concept" }, { t: "Sandals Golf and Country Club Jamaica", s: "Owned by Sandals" }, { t: "Sandals House Jamaica", s: "Elevated to highest level" }] },
  { id: "st-lucia", name: "St. Lucia", country: "St. Lucia", haul: 2, budget: 3, climate: ["hot"], setting: ["ocean", "mountain"], villa: 1, kids: 1, nightlife: 1, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "The Pitons make every milestone dinner feel epic; made for celebration trips.", sig: ["Pitons sail", "mud baths", "chocolate estate"], picks: [{ t: "Sandals Golf Course St. Lucia", s: "Green fees complimentary for guests" }, { t: "Sandals Grill St. Lucia", s: "New restaurant (Bokan) with chef-led platters and farm-to-table dining" }, { t: "Sandals Royal Jamaica St. Lucia Villa Top", s: "New ocean-view two-story one-bedroom butler villa with private pool" }] },
  { id: "turks-caicos", name: "Turks & Caicos", country: "Turks & Caicos", haul: 2, budget: 4, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 0, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "Grace Bay's calm shallow water is the safest, prettiest big-family beach anywhere.", sig: ["boat day to iguana cay", "conch shack", "snorkeling"], picks: [{ t: "Beaches Turks and Caicos", s: "859 rooms" }] },
  { id: "bahamas", name: "Nassau & Paradise Island", country: "Bahamas", haul: 1, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 2, nightlife: 1, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "Quick flights, big resorts, and private-island beach days close to home.", sig: ["beach club day", "Atlantis waterpark", "swimming pigs"], picks: [{ t: "Perfect Day at Coco Cay", s: "Private all-inclusive resort for cruise day" }, { t: "Royal Beach Club Nassau Paradise Island", s: "Private beach club experience on Nassau" }, { t: "Sandals Royal Bahamas", s: "Island inclusive dining program ($250 off-resort credit, transfers included)" }] },
  { id: "curacao", name: "Cura\u00e7ao", country: "Cura\u00e7ao", haul: 2, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 1, nightlife: 1, usNoPassport: false, months: "Best year-round (outside hurricane belt)", blurb: "Outside the hurricane belt with Dutch-Caribbean color and fresh new resorts.", sig: ["snorkeling", "Willemstad old town", "beach hopping"], picks: [{ t: "Sandals Couturier", s: "Renovated to highest level" }, { t: "Sandals Royal Curacao", s: "New roundabouts added" }] },
  { id: "costa-rica", name: "Guanacaste & Arenal", country: "Costa Rica", haul: 2, budget: 2, climate: ["hot", "warm"], setting: ["ocean", "mountain"], villa: 2, kids: 2, nightlife: 1, usNoPassport: false, months: "Best Nov\u2013Apr", blurb: "Surf mornings, sloth afternoons, hot-spring nights: adventure that works for all ages.", sig: ["zipline", "catamaran sunset", "hot springs"], picks: [{ t: "Colette Costa Rica Tour", s: "Small groups" }, { t: "Intrepid Premium Family Costa Rica", s: "7 days" }] },
  { id: "belize", name: "Ambergris Caye", country: "Belize", haul: 1, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 1, nightlife: 1, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "English-speaking, reef-wrapped, golf-cart paced: easy adventure for mixed groups.", sig: ["Hol Chan snorkel", "Mayan ruins", "cave tubing"] },
  { id: "maui", name: "Maui", country: "Hawaii, USA", haul: 3, budget: 3, climate: ["warm"], setting: ["ocean"], villa: 1, kids: 2, nightlife: 0, usNoPassport: true, months: "Best Apr\u2013May, Sep\u2013Oct", blurb: "No passports, epic mornings, whale season: the far-away trip that's still home.", sig: ["Road to Hana", "Molokini snorkel", "luau"] },
  { id: "oahu", name: "Oahu", country: "Hawaii, USA", haul: 3, budget: 3, climate: ["warm"], setting: ["ocean", "city"], villa: 1, kids: 2, nightlife: 1, usNoPassport: true, months: "Best Apr\u2013Jun, Sep\u2013Nov", blurb: "Pearl Harbor history plus Waikiki ease: the multigenerational crowd-pleaser.", sig: ["Pearl Harbor", "North Shore day", "surf lessons"] },
  { id: "30a", name: "Destin & 30A", country: "Florida, USA", haul: 1, budget: 1, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 1, usNoPassport: true, months: "Best May\u2013Sep", blurb: "Drive-in beach week with purpose-built 10-bedroom homes and golf-cart evenings.", sig: ["pontoon to Crab Island", "beach week", "deep-sea fishing"] },
  { id: "outer-banks", name: "Outer Banks", country: "North Carolina, USA", haul: 1, budget: 1, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 0, usNoPassport: true, months: "Best Jun\u2013Sep", blurb: "The reunion capital of the East Coast: one giant house, one long beach.", sig: ["wild horses 4x4", "lighthouses", "dune hang-gliding"] },
  { id: "hilton-head", name: "Hilton Head", country: "South Carolina, USA", haul: 1, budget: 1, climate: ["hot", "warm"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 0, usNoPassport: true, months: "Best Apr\u2013Oct", blurb: "Bikes, tides, and golf: the gentlest big-family beach week in the South.", sig: ["golf", "dolphin cruise", "low-country boil"] },
  { id: "algarve", name: "The Algarve", country: "Portugal", haul: 3, budget: 2, climate: ["hot"], setting: ["ocean"], villa: 2, kids: 2, nightlife: 1, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Oct", blurb: "Europe's best villa-with-pool value, with sea caves at the end of every road.", sig: ["Benagil caves boat", "cliff walks", "winery day"] },
  { id: "lisbon", name: "Lisbon", country: "Portugal", haul: 3, budget: 2, climate: ["warm"], setting: ["city"], villa: 1, kids: 1, nightlife: 2, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Oct", blurb: "The friendliest-priced great city in Western Europe, with beaches a train away.", sig: ["Sintra day trip", "food tour", "fado night"], picks: [{ t: "Exodus Premium Northern Portugal", s: "Activity level 1 (easy, 2km walks)" }, { t: "G Adventures G-Lux Portugal Coastal Walk Douro", s: "Lisbon to Bordeaux coastal hiking" }] },
  { id: "tuscany", name: "Tuscany", country: "Italy", haul: 3, budget: 3, climate: ["warm"], setting: ["country"], villa: 2, kids: 2, nightlife: 0, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Oct", blurb: "One villa, one pool, one long table: the group trip people dream about.", sig: ["private chef pasta night", "Chianti wine tour", "Siena day trip"] },
  { id: "amalfi", name: "Amalfi Coast", country: "Italy", haul: 3, budget: 4, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 0, nightlife: 1, usNoPassport: false, months: "Best May\u2013Jun, Sep", blurb: "The milestone-birthday coastline: boat days to Capri and dinners over the sea.", sig: ["private boat to Capri", "limoncello lunch", "Path of the Gods"] },
  { id: "puglia", name: "Puglia", country: "Italy", haul: 3, budget: 2, climate: ["hot"], setting: ["country", "ocean"], villa: 2, kids: 2, nightlife: 0, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Oct", blurb: "Masseria farm-estates built for twelve, at half of Tuscany's price.", sig: ["orecchiette class", "Polignano boat day", "olive-oil tasting"] },
  { id: "rome", name: "Rome", country: "Italy", haul: 3, budget: 3, climate: ["hot", "warm"], setting: ["city"], villa: 0, kids: 2, nightlife: 1, usNoPassport: false, months: "Best Apr\u2013May, Oct", blurb: "Gladiators and gelato: the city that works for age 8 and age 80 alike.", sig: ["Colosseum tour", "pasta class", "Trastevere crawl"], picks: [{ t: "Belmond Caruso Amalfi Coast", s: "Located in Ravello" }, { t: "Belmond Cipriani Venice", s: "Private Cipriani boat to St. Mark's Square" }, { t: "Belmond Grand Hotel Timeo Taormina", s: "Located in Taormina town" }] },
  { id: "crete", name: "Crete", country: "Greece", haul: 3, budget: 2, climate: ["hot"], setting: ["ocean", "mountain"], villa: 2, kids: 2, nightlife: 1, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Oct", blurb: "Greek villa value with sandy beaches, gorges, and tavernas that adopt your kids.", sig: ["Balos boat day", "Samaria Gorge", "taverna nights"], picks: [{ t: "Royal Beach Club Santorini Europe", s: "First European private beach club" }] },
  { id: "paros", name: "Paros", country: "Greece", haul: 3, budget: 3, climate: ["hot"], setting: ["ocean"], villa: 1, kids: 1, nightlife: 2, usNoPassport: false, months: "Best late May\u2013Jun, Sep", blurb: "The Cyclades without the Mykonos markup; Naoussa dinners are the point.", sig: ["Antiparos boat day", "windsurfing", "harbor dinners"] },
  { id: "croatia", name: "Split & Hvar", country: "Croatia", haul: 3, budget: 2, climate: ["hot"], setting: ["ocean", "city"], villa: 2, kids: 1, nightlife: 2, usNoPassport: false, months: "Best late May\u2013Jun, Sep", blurb: "Sail-week energy: island villas, Blue Cave boat days, old-town nights.", sig: ["group catamaran day", "Blue Cave", "waterfall day trip"] },
  { id: "provence", name: "Provence", country: "France", haul: 3, budget: 3, climate: ["warm"], setting: ["country"], villa: 2, kids: 2, nightlife: 0, usNoPassport: false, months: "Best May\u2013Jun, Sep", blurb: "A stone farmhouse, market mornings, ros\u00e9 afternoons: France at group pace.", sig: ["market mornings", "wine tour with driver", "lavender fields (late Jun\u2013Jul)"] },
  { id: "barcelona", name: "Barcelona & Costa Brava", country: "Spain", haul: 3, budget: 2, climate: ["hot"], setting: ["city", "ocean"], villa: 1, kids: 1, nightlife: 2, usNoPassport: false, months: "Best May\u2013Jun, Sep", blurb: "Gaud\u00ed by day, tapas by night, coves up the coast for the villa crowd.", sig: ["tapas crawl", "Sagrada Fam\u00edlia", "sailing day"] },
  { id: "ireland", name: "Ireland", country: "Ireland", haul: 3, budget: 2, climate: ["crisp"], setting: ["country", "city"], villa: 1, kids: 2, nightlife: 1, usNoPassport: false, months: "Best May\u2013Sep", blurb: "Castles, coastlines, and pubs: the heritage trip whole families cross oceans for.", sig: ["castle stays", "Cliffs of Moher", "trad music night"], picks: [{ t: "Irish Supreme Five-Star Castle Tour", s: "Five-star tour staying in castles and five-star manor hotels with five-star m\u2026" }] },
  { id: "prague", name: "Prague & Bohemia", country: "Czech Republic", haul: 3, budget: 2, climate: ["crisp"], setting: ["city"], villa: 0, kids: 1, nightlife: 2, usNoPassport: false, months: "Best May\u2013Jun, Sep\u2013Dec", blurb: "Fairy-tale streets and castle country, with insider doors Gatherwell can open.", sig: ["old town private tours", "\u010cesk\u00fd Krumlov day", "beer halls"], picks: [{ t: "Astronomical Clock Private Access Prague", s: "Private access with Clock Master" }, { t: "Cesk\u00fd Krumlov Castle Private Tour", s: "UNESCO heritage site" }, { t: "Clementine Library Prague", s: "Features in Dan Brown's 'Secrets of Secrets' novel" }] },
  { id: "london", name: "London", country: "England", haul: 3, budget: 4, climate: ["crisp"], setting: ["city"], villa: 0, kids: 2, nightlife: 2, usNoPassport: false, months: "Best May\u2013Sep, Dec", blurb: "Theatre, football, museums: the big-city trip that needs no translation.", sig: ["West End show", "football match", "Borough Market"] },
  { id: "paris", name: "Paris", country: "France", haul: 3, budget: 4, climate: ["warm", "crisp"], setting: ["city"], villa: 0, kids: 2, nightlife: 2, usNoPassport: false, months: "Best Apr\u2013Jun, Sep\u2013Oct", blurb: "The icon city: Seine dinner cruise for the group, croissants for the kids.", sig: ["Seine dinner cruise", "Versailles day", "market + cooking class"] },
  { id: "banff", name: "Banff & Canmore", country: "Canada", haul: 2, budget: 3, climate: ["crisp", "snow"], setting: ["mountain"], villa: 1, kids: 2, nightlife: 0, usNoPassport: false, months: "Jun\u2013Sep hikes \u00b7 Dec\u2013Mar ski", blurb: "Turquoise lakes and gondola views: the mountain trip that needs no hiking boots.", sig: ["Lake Louise", "gondola + hot springs", "canoe day"] },
  { id: "breckenridge", name: "Breckenridge", country: "Colorado, USA", haul: 2, budget: 2, climate: ["snow", "crisp"], setting: ["mountain"], villa: 2, kids: 2, nightlife: 1, usNoPassport: true, months: "Ski Dec\u2013Mar \u00b7 summer Jun\u2013Sep", blurb: "Ski-chalet Christmases and hot-tub summers, two hours from Denver.", sig: ["ski week", "snowmobiling", "summer rafting"] },
  { id: "smoky-mountains", name: "Smoky Mountains", country: "Tennessee, USA", haul: 1, budget: 1, climate: ["crisp", "warm"], setting: ["mountain"], villa: 2, kids: 2, nightlife: 0, usNoPassport: true, months: "Best Apr\u2013Jun, Sep\u2013Nov", blurb: "Mega-cabins with theaters and game rooms: the cheapest big-group week in America.", sig: ["national park hikes", "Dollywood", "cabin game nights"] },
  { id: "whistler", name: "Whistler", country: "Canada", haul: 2, budget: 3, climate: ["snow", "crisp"], setting: ["mountain"], villa: 2, kids: 2, nightlife: 2, usNoPassport: false, months: "Ski Nov\u2013Apr \u00b7 summer Jun\u2013Sep", blurb: "North America's biggest resort with a walkable village made for groups.", sig: ["ski/board", "Peak2Peak gondola", "spa day"] },
  { id: "utah-parks", name: "Zion & Moab", country: "Utah, USA", haul: 2, budget: 1, climate: ["crisp", "hot"], setting: ["mountain"], villa: 1, kids: 2, nightlife: 0, usNoPassport: true, months: "Best Apr\u2013May, Sep\u2013Oct", blurb: "Red-rock mornings and dark-sky nights across America's mightiest parks.", sig: ["Zion Narrows", "Arches sunrise", "4x4 tour"] },
  { id: "mexico-city", name: "Mexico City", country: "Mexico", haul: 2, budget: 1, climate: ["warm"], setting: ["city"], villa: 0, kids: 1, nightlife: 2, usNoPassport: false, months: "Best Oct\u2013May", blurb: "The best food-per-dollar city in North America, with pyramids up the road.", sig: ["taco tour", "Teotihuac\u00e1n + balloon", "Lucha Libre night"] },
  { id: "new-orleans", name: "New Orleans", country: "Louisiana, USA", haul: 1, budget: 1, climate: ["hot", "warm"], setting: ["city"], villa: 1, kids: 1, nightlife: 2, usNoPassport: true, months: "Best Oct\u2013Apr", blurb: "Jazz, gumbo, and second lines: the celebration city.", sig: ["private jazz night", "swamp tour", "cooking class"] },
  { id: "nashville", name: "Nashville", country: "Tennessee, USA", haul: 1, budget: 1, climate: ["warm", "hot"], setting: ["city"], villa: 2, kids: 0, nightlife: 2, usNoPassport: true, months: "Best Apr\u2013Jun, Sep\u2013Oct", blurb: "Purpose-built party houses and honky-tonks: the friends-trip capital.", sig: ["Broadway night", "songwriter round", "hot-chicken crawl"] },
  { id: "charleston", name: "Charleston", country: "South Carolina, USA", haul: 1, budget: 2, climate: ["warm", "hot"], setting: ["city", "ocean"], villa: 1, kids: 2, nightlife: 1, usNoPassport: true, months: "Best Mar\u2013May, Sep\u2013Nov", blurb: "Oyster roasts and porch evenings, with a beach house twenty minutes away.", sig: ["food tour", "harbor boat day", "Isle of Palms beach day"] },
  { id: "scottsdale", name: "Scottsdale", country: "Arizona, USA", haul: 1, budget: 2, climate: ["hot"], setting: ["country"], villa: 2, kids: 1, nightlife: 2, usNoPassport: true, months: "Best Oct\u2013Apr", blurb: "Desert pool houses, golf, and Old Town nights: the easy Southwest gathering.", sig: ["pool day", "Camelback hike", "hot-air balloon"] },
  { id: "napa", name: "Napa & Sonoma", country: "California, USA", haul: 2, budget: 4, climate: ["warm"], setting: ["country"], villa: 1, kids: 0, nightlife: 0, usNoPassport: true, months: "Best May\u2013Oct", blurb: "Vineyard tables and driver-guided tastings for the grown-up milestone.", sig: ["wine tour with driver", "balloon at dawn", "farm dinner"] },
  { id: "egypt-nile", name: "Nile Cruise", country: "Egypt", haul: 3, budget: 3, climate: ["hot"], setting: ["city"], villa: 0, kids: 2, nightlife: 0, usNoPassport: false, months: "Best Oct\u2013Apr", blurb: "Pyramids to Luxor by boutique river ship: the once-in-a-lifetime family history trip.", sig: ["pyramids", "Valley of the Kings", "river ship life"], picks: [{ t: "AmaWaterways Nile River Egypt", s: "72-guest vessels" }, { t: "G Adventures National Geographic Journeys Egypt", s: "Discover Egypt 10 days" }] },
  { id: "morocco", name: "Marrakech & Beyond", country: "Morocco", haul: 3, budget: 2, climate: ["hot", "warm"], setting: ["city", "country"], villa: 1, kids: 1, nightlife: 1, usNoPassport: false, months: "Best Mar\u2013May, Sep\u2013Nov", blurb: "Riads, souks, and desert camps: the adventure that feels like another world.", sig: ["souk food tour", "Atlas day trip", "desert camp night"], picks: [{ t: "G Adventures National Geographic Journeys Morocco", s: "Storytellers and cuisine learning" }, { t: "Intrepid Premium Family Morocco", s: "10 days" }] },
  { id: "peru", name: "Sacred Valley & Machu Picchu", country: "Peru", haul: 3, budget: 2, climate: ["crisp"], setting: ["mountain"], villa: 0, kids: 1, nightlife: 0, usNoPassport: false, months: "Best May\u2013Sep", blurb: "The bucket-list trek, doable by train: wonder for every generation.", sig: ["Machu Picchu", "Sacred Valley", "Cusco food scene"], picks: [{ t: "Big Five Tours Peru Iscas North", s: "Accessible via Chiclayo (3-hour drive)" }, { t: "G Adventures National Geographic Journeys Peru", s: "Peru #1 destination (20k people/year)" }, { t: "G Adventures National Geographic Signature Peru Machu Picchu", s: "Five-star accommodation, upgraded meals, behind-scenes access, exclusive priv\u2026" }] },
  { id: "cartagena", name: "Cartagena", country: "Colombia", haul: 2, budget: 2, climate: ["hot"], setting: ["city", "ocean"], villa: 1, kids: 1, nightlife: 2, usNoPassport: false, months: "Best Dec\u2013Apr", blurb: "Walled-city color, rooftop dinners, and Rosario Islands boat days.", sig: ["old-city food tour", "Rosario Islands day", "salsa night"], picks: [{ t: "AmaWaterways Magdalena River Colombia", s: "Only river cruise operator" }, { t: "Big Five Tours Colombia", s: "Emerging destination with authentic experiences" }, { t: "Colette Colombia Extension", s: "Extension available from Costa Rica" }] },
  { id: "new-zealand", name: "New Zealand", country: "New Zealand", haul: 3, budget: 3, climate: ["crisp"], setting: ["mountain", "ocean"], villa: 1, kids: 2, nightlife: 1, usNoPassport: false, months: "Best Nov\u2013Mar", blurb: "The far-away adventure that rewards a long trip: fjords, thrills, and wine.", sig: ["Milford Sound", "Queenstown thrills", "wine region day"], picks: [{ t: "Flock Hill Lodge", s: "36,000 acres with world-class culinary program" }, { t: "Otahuna Lodge", s: "Over 1 million bulbs including spectacular daffodils" }, { t: "Milford Sound Helicopter Tours", s: "Exclusive access to Urnfulgurn with only 6000 people/year versus 200000+ at M\u2026" }] },
];
